Repository nomtek/mistralai_client_dart, pull requests merged in 2024-01, with the labels that each got.

#12 Implement list models method + abstract get request function
  lib/src/mistralai_client_dart_base.dart
  lib/src/models/list_models_result.dart
  lib/src/models/list_models_result.g.dart
  lib/src/models/models.dart
Labels: enhancement

#16 7 implement embeddings method
  lib/src/mistralai_client_dart_base.dart
  lib/src/models/embeddings.dart
Labels: enhancement

#26 Add pull request template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#24 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#18 #13 refactor and clean up code
  lib/mistralai_client_dart.dart
  lib/src/exceptions.dart
  lib/src/mistralai_client_dart_base.dart
  lib/src/models/chat_completion.dart
  lib/src/models/chat_completion.g.dart
  lib/src/models/chat_params.dart
  lib/src/models/embeddings.dart
  lib/src/models/embeddings.g.dart
  lib/src/models/mappers.dart
  lib/src/network/request.dart
  lib/src/network/url_tools.dart
  test/mistralai_client_dart_test.dart
  test/src/common_tests.dart
  test/src/fakes.dart
  test/src/fixtures.dart
  test/src/mistralai_client_dart_base_chat_stream_test.dart
  test/src/mistralai_client_dart_base_chat_test.dart
  test/src/mistralai_client_dart_base_embeddings_test.dart
  test/src/mistralai_client_dart_base_list_models_test.dart
  test/src/models/chat_params_test.dart
  test/src/network/mistralai_url_factory_test.dart
Labels: code quality

#29 Fix pull request template not automatically filling PR form
  .github/pull_request_template.md
Labels: bug, documentation

#27 Prepare the project for release to pub.dev
  CHANGELOG.md
  README.md
  example/mistralai_client_dart_example.dart
  lib/src/models/embeddings.dart
  lib/src/models/embeddings.g.dart
  pubspec.yaml
  test/src/mistralai_client_dart_base_embeddings_test.dart
Labels: documentation, code quality

#34 Update `pubspec.yaml` description
  pubspec.yaml
Labels: documentation

#33 Add topics to `pubspec.yaml`
  pubspec.yaml
Labels: documentation

#36 Update package version + update changelog
  CHANGELOG.md
  pubspec.yaml
Labels: documentation
